# We are going to depend on stack for ghc and cabal. There is no need to
# set the language to haskell, stack will get the compiler we need and we'll
# cache it.
language: generic
sudo: false

before_install:
  - if [ ! -x ~/.local/bin/stack ]; then
        mkdir -p ~/.local/bin;
        travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
            | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - export PATH=$HOME/.local/bin:$PATH
  - stack --version
  - stack --no-terminal setup
  - stack exec -- ghc --version

install:
  - travis_wait 30 stack --no-terminal build --haddock --only-dependencies

script:
  - stack --no-terminal build --haddock
  - mv "$(stack --no-terminal path --dist-dir)"/doc/html/fits-parse .haddocks

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.stack/
    - $HOME/.local/
    - .stack-work/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES_TOKEN
  keep-history: true
  local-dir: .haddocks/
  on:
    branch: master
