name:                fits-parse
version:             0.0.1
#synopsis:
#description:
homepage:            https://github.com/krakrjak/fits-parse#readme
license:             BSD2
author:              Zac Slade
maintainer:          krakrjak@gmail.com
copyright:           Copyright (c) 2018 Zac Slade
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - megaparsec
  - liquidhaskell

library:
  source-dirs: src
  dependencies:
      - data-default

executables:
  fits-render:
    source-dirs:      app
    main:             Main.hs
    dependencies:
        - fits-parse
        - optparse-applicative
        - JuicyPixels
        - fast-logger
