name:                fits-parse
version:             0.1.0
synopsis:            Parse FITS files
description:         Parse and manipulate FITS data natively in Haskell
homepage:            https://github.com/krakrjak/fits-parse#readme
license:             BSD2
author:              Zac Slade
maintainer:          krakrjak@gmail.com
copyright:           Copyright (c) 2019 Zac Slade
category:            Science
extra-source-files:
  - README.md
  - docs/Makefile
  - docs/make.bat
  - docs/conf.py
  - docs/index.rst
  - docs/examples/omnibus.rst

flags:
  examples:
    description: Do you want to build the examples?
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5
  - bytestring

library:
  source-dirs: src
  dependencies:
      - data-default
      - text
      - megaparsec
      - text-latin1
      - parser-combinators
      - binary

executables:
  omnibus:
    when:
      - condition: flag(examples)
        buildable: true
    source-dirs: examples/omnibus
    main: Main.hs
    dependencies:
    - fits-parse
    - optparse-applicative
    - JuicyPixels
    - fast-logger
    - vector
    - statistics
