resolver: lts-23.0
pvp-bounds: both

### Uncomment the next three lines to build the examples
#flags:
#  fits-parse:
#    examples: true
## A one liner `stack build --flag fits-parse:examples`

packages:
    - .
