resolver: nightly-2018-12-08

allow-newer: false
compiler: ghc-8.4.3

packages:
    - .

extra-deps:
    - base-compat-0.9.3
    - aeson-1.2.4.0

    - github: ucsd-progsys/liquidhaskell
      commit: 2820b7530ddd09e289c60df4ce085faa7c507231 
      #^^ wants ghc-8.4.3 not ghc-8.4.4 - allow-newer: true

    - github: ucsd-progsys/liquid-fixpoint
      commit: d58bc42e0de71920629c7d57e8cae82e3b6136ac
      #^^ Needed as there is a fix for ghc-8.4 just off the tip of 0.7.0.7

    - text-format-0.3.2
    - dotgen-0.4.2
    - fgl-visualize-0.1.0.1
    - fgl-5.7.0.1
    - located-base-0.1.1.1
